
// q = question, a = answer(s), s = source 
window.questions = [
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Supervised learning is a type of machine learning where a function is inferred from labeled training data. ", "a": ["Yes", "No"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "The training data in a supervised machine learning contains of a set of training examples.", "a": ["Yes", "No"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Decision Trees is a supervised machine learning algorithm", "a": ["Yes", "No"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "K-nearest Neighbor is a supervised machine learning algorithm", "a": ["Yes", "No"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Support Vector Machine is a supervised machine learning algorithm", "a": ["Yes", "No"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Neuronal Network are used only for supersived machine learning problems", "a": ["No", "Yes"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Clustering is a typical supervised machine learning task", "a": ["No", "Yes"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Regression algorithms are used on unsupervised problems", "a": ["No", "Yes"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Anonamly detection is a topic for unsupervised learning algorithms", "a": ["Yes", "No"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Unsupervised Learning enables classification", "a": ["Yes", "No"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Supervised learning enables classification and Regression", "a": ["Yes", "No"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Unsupervised Learning enables dimension reduction", "a": ["Yes", "No"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Unsupervised Learning not enables density estimation", "a": ["No", "Yes"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "While supervised learning is used in analysis, unsupervised learning finds use in prediction", "a": ["No", "Yes"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "What do you understand by the Selection Bias? Selection bias is typically associated with research that doesn\u2019t have a random selection of participants. It is a type of error that occurs when a researcher decides who is going to be studied.", "a": ["Yes", "No"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Time Interval - A systematic error resulting due to a non-random sample of a populace causing certain members of the same to be less likely included than others that results in a biased sample", "a": ["No", "Yes"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Sampling Bias -  A trial might be ended at an extreme value, usually due to ethical reasons, but the extreme value is most likely to be reached by the variable with the most variance, even though all variables have a similar mean.", "a": ["No", "Yes"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Please explain the goal of A/B Testing. - A/B Testing is a statistical hypothesis testing meant for a randomized experiment with two variables, A and B. The goal of A/B Testing is to minimize the likelihood of an outcome of some interest by identifying any changes to a webpage.", "a": ["No", "Yes"]},
{"s": "https://en.wikipedia.org/wiki/F-score", "q": "What is the best possible value of F-Score", "a": ["1", "0", "1", "inf"]},
{"s": "https://en.wikipedia.org/wiki/F-score", "q": "What is the worst possible value of F-Score", "a": ["0", "1", "2", "-inf"]},
{"s": "https://en.wikipedia.org/wiki/F-score", "q": "F Beta is defined as", "a": ["(1 + beta ^2) * ((precision * recall) / (beta^2 * precision) + recall)", "(1 * beta ^2) * ((precision + recall) / (beta^2 + precision) * recall)", "(1 + beta ^3) * ((precision * recall) / (beta^3 * precision) + recall)", "(1 + beta ^2) * ((precision * recall) / (beta^2 * precision) - recall)"]},
{"s": "https://en.wikipedia.org/wiki/False_positives_and_false_negatives#true_positive", "q": "A false positive is an error in binary classification in which a test result incorrectly indicates the presence of a condition such as a disease when the disease is not present", "a": ["Yes", "No"]},
{"s": "https://en.wikipedia.org/wiki/False_positives_and_false_negatives#true_positive", "q": "false negative is the error where the test result incorrectly indicates the absence of a condition when it is actually present", "a": ["Yes", "No"]},
{"s": "https://en.wikipedia.org/wiki/F-score", "q": "False negative is references as type 1 error", "a": ["No", "Yes"]},
{"s": "https://en.wikipedia.org/wiki/F-score", "q": "false positive is references as type 1 error", "a": ["yes", "No"]},
{"s": "https://en.wikipedia.org/wiki/F-score", "q": "Accuracy is defined as", "a": ["(True positive + True Negative) / (positive + negative)", "(True positive - True Negative) / (positive + negative)", "(True positive + True Negative) / (positive - negative)", "(True positive + True Negative) * (positive + negative)"]},
{"s": "https://en.wikipedia.org/wiki/Matthews_correlation_coefficient", "q": "Matthews correlation coefficient (MCC) is defined as ((true positive * ture negative) - (false positive * false negative)) / ((true positive + false postive) * (true positive + false negative) * (true negative * false positive) * (true negative + false negative))", "a": ["Yes", "No"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Overfitting occurs when trying to fit a linear model to non-linear data.", "a": ["No", "Yes"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "What is the common amount of time used for data cleaning in data analysis", "a": ["80%", "20%", "40%", "60%"]},
{"s": "https://hackr.io/blog/data-science-interview-questions", "q": "Data cleaning increases the accuracy of a machine learning model", "a": ["Yes", "No"]},
{"s": NaN, "q": "What is a common train - test split ratio?", "a": ["0,8 / 0,2", "0,2 / 0,8"]},
{"s": "STOP", "q": "lease enumerate the various steps involved in an analytics project.", "a": [NaN, NaN]},
]